# Calculate Habitat Priorities with Habicon

```{r}
source("setup.R")
```

Load Habicon:

```{r eval=FALSE}
devtools::install_github("ccmothes/habicon")
```

```{r}
library(habicon)
```

## Read in suitability and connectivity maps

```{r}
# suitability
suit_maps <- map(
  list.dirs("data/output_sdm_2025-04-01/", recursive = FALSE),
  ~ list.files(.x, pattern = ".tif", full.names = TRUE)
) %>%
  map(function(x) {
    r <- terra::rast(x)
    crs(r) <- "EPSG:26913"
    
    return(r)
  })

# connectivity
con_dirs <- list.dirs("data/output_connectivity/", recursive = FALSE)

## pull max date
max_date <-  str_extract(con_dirs, "\\d{4}-\\d{2}-\\d{2}") %>% max(.)

corr_maps <- map(con_dirs[str_detect(con_dirs, max_date)], function(x) {
  r <- terra::rast(paste0(x, "/cum_currmap.tif"))
  crs(r) <- "EPSG:26913"
  return(r)
})

# resistance layers used for connectivity
resist_maps <-  map(list.files(
  "data/output_resistance_2025-04-02//",
  pattern = ".tif",
  full.names = TRUE
), function(x) {
  r <- terra::rast(x)
  crs(r) <- "EPSG:26913"
  return(r)
})
```

### Set up parameters

```{r}
# for saving later

## species name vector
species <- map(suit_maps,
  ~ terra::sources(.x) %>%
    basename() %>%
    tools::file_path_sans_ext() %>% str_remove("_prediction")
)

## path to save outputs
output_path <- paste0("data/output_habicon_", Sys.Date())

if(!dir.exists(output_path)) {
  dir.create(output_path)
}


# Species Dispersal Distances (retrieved from NIC 2019 report) CHECK ORDER
distance <- c(422, 1300, 3219, 805, 281, 305, 16093)
```

## Prep Maps

```{r}
# using top 20% of suitability/connectivity values
suit_bin <-  map(suit_maps, ~bin_map(.x, threshold = quantile(terra::values(.x, na.rm = TRUE), 0.85)))

corr_bin <- map(corr_maps, ~bin_map(.x, threshold = quantile(terra::values(.x, na.rm = TRUE), 0.85)))

```

Visualize

```{r}
map(suit_bin, qtm)

map(corr_bin, qtm)
```

## Calculate Patch Priority

```{r}
start <- Sys.time()

patches <- vector("list", length = length(species))

for (i in 1:length(species)) {
  patches[[i]] <- patch_priority(
    suit = suit_maps[[i]],
    suit_bin = suit_bin[[i]],
    corr_bin = corr_bin[[i]],
    resist = resist_maps[[i]],
    d = distance[i],
    progress = TRUE
  )
  
}


end <- Sys.time()

end - start
```

### View and Save Outputs

View:

```{r}
patch_maps <- vector("list", length = length(patches))

for (i in 1:length(species)){
  
  patch_maps[[i]] <- keep(patches[[i]], ~inherits(.x, "SpatRaster")) %>%
    rast()
}

map(patch_maps, plot)
```

Save:

```{r}
# save patch priority raster stack
for (i in 1:length(species)){
  
  keep(patches[[i]], ~inherits(.x, "SpatRaster")) %>% 
    rast() %>% 
    writeRaster(filename = paste0(output_path, "/", species[i], "_patch_priority.tif"), overwrite = TRUE)
  
}

# save data frames
for (i in 1:length(species)){
  
  keep(patches[[i]], ~inherits(.x, "data.frame")) %>% 
    bind_rows() %>% 
    write_csv(file = paste0(output_path, "/", species[i], "_patch_priority_table.csv"))
  
}

```

## Calculate Corridor Priority

```{r}
start <- Sys.time()

corridors <- vector("list", length = length(species))

for (i in 1:length(species)) {
  corridors[[i]] <- corr_priority(
    suit = suit_maps[[i]],
    suit_bin = suit_bin[[i]],
    corr_bin = corr_bin[[i]],
    resist = resist_maps[[i]],
    d = distance[i],
    progress = TRUE
  )
  
}


end <- Sys.time()

end - start
```

### View and Save

View:

```{r}
map(corridors, qtm)
```

Save:

```{r}
walk2(corridors, species, function(x, y) {
  # assign informative names
  terra::set.names(x, paste0(y, "_corr_priority"))

  # save raster
  writeRaster(x, filename = paste0(output_path, "/", y, "_corridor_priority.tif"), overwrite = TRUE)
})

```

# Rerun for certain species

## Painted Lady

Define parameters

```{r}
suit_map <- terra::rast("data/output_sdm_2025-03-03/Vanessa cardui/Vanessa_cardui_prediction.tif")
crs(suit_map) <- "EPSG:26913"

corr_map <- terra::rast("data/output_connectivity/Vanessa_cardui_2025-04-08/cum_currmap.tif")

crs(corr_map) <- "EPSG:26913"

resist_map <- terra::rast("data/output_resistance_2025-04-08/Vanessa_cardui_prediction_resistance.tif")
crs(resist_map) <- "EPSG:26913"


## create bin maps
suit_bin <-  bin_map(suit_map, threshold = quantile(terra::values(suit_map, na.rm = TRUE), 0.85))

corr_bin <- bin_map(corr_map, threshold = quantile(terra::values(corr_map, na.rm = TRUE), 0.85))


## species name vector
species <- terra::sources(suit_map) %>%
    basename() %>%
    tools::file_path_sans_ext() %>% str_remove("_prediction")

## path to save outputs
output_path <- paste0("data/output_habicon_", Sys.Date())

if(!dir.exists(output_path)) {
  dir.create(output_path)
}
```

#### Patch Priority

```{r}
v_carduri_patches <- patch_priority(
    suit = suit_map,
    suit_bin = suit_bin,
    corr_bin = corr_bin,
    resist = resist_map,
    d = 16093,
    progress = TRUE
  )
```

#### Corridor Priority

```{r}
v_carduri_corr <- corr_priority(
    suit = suit_map,
    suit_bin = suit_bin,
    corr_bin = corr_bin,
    resist = resist_map,
    d = 16093,
    progress = TRUE
  )
```

#### Save outputs

```{r}
# save patch priority raster stack
keep(v_carduri_patches, ~ inherits(.x, "SpatRaster")) %>%
  rast() %>%
  writeRaster(
    filename = paste0(output_path, "/", species, "_patch_priority.tif"),
    overwrite = TRUE
  )

# save data frames
keep(v_carduri_patches, ~ inherits(.x, "data.frame")) %>%
  bind_rows() %>%
  write_csv(file = paste0(output_path, "/", species, "_patch_priority_table.csv"))

# Save corr priority raster
terra::set.names(v_carduri_corr, paste0(species, "_corr_priority"))
writeRaster(v_carduri_corr, filename = paste0(output_path, "/", species, "_corridor_priority.tif"), overwrite = TRUE)
```
