# Prep Data for Shiny App

```{r}
source("setup.R")
```

## App Maps

#### Patches

```{r}
# app patch maps
patch_maps <- map(
  list.files(
    "data/output_habicon_2025-04-28/",
    pattern = "patch_priority.tif",
    full.names = TRUE
  ),
  terra::rast
)

## replace V. cardui update
# patch_maps[[8]] <- terra::rast("data/output_habicon_2025-04-08/Vanessa_cardui_patch_priority.tif")
# 

# save to app
map(patch_maps, ~writeRaster(.x, filename = paste0("shiny/app_data/output_habicon/", tools::file_path_sans_ext(basename(sources(.x))), ".tif"), overwrite = TRUE))
```

#### Corridors

```{r}
# app patch maps
corr_maps <- map(
  list.files(
    "data/output_habicon_2025-04-28/",
    pattern = "corridor_priority.tif",
    full.names = TRUE
  ),
  terra::rast
)

## replace V. cardui update
# corr_maps[[8]] <- terra::rast("data/output_habicon_2025-04-08/Vanessa_cardui_corridor_priority.tif")


# save to app
map(corr_maps, ~writeRaster(.x, filename = paste0("shiny/app_data/output_habicon/", tools::file_path_sans_ext(basename(sources(.x))), ".tif"), overwrite = TRUE))
```

# Richness Maps

```{r}
## rescale values to sum all together
rescale_function <- function(x) {
  map(names(x), ~ x[[.x]] %>% habicon::rescale_map()) %>% 
    do.call(c, .)
}

# patch priority

## V Cardui is is different extent...
# patch_maps[[8]] <- patch_maps[[8]] %>% 
#   resample(patch_maps[[1]])

patch_rescale <- map(patch_maps, rescale_function) %>%
  # reduce to single spatraster
  do.call(c, .)


patch_sum <- map(c("qwa", "btwn", "dECA"), function(x) {
  r <- subset(patch_rescale, grep(x, names(patch_rescale))) %>%
    sum(na.rm = TRUE)
  
  names(r) <- x
  
  return(r)
}) %>% do.call(c, .)


# corridor priority

# V cardui match extent
# corr_maps[[8]] <- corr_maps[[8]] %>% 
#   resample(corr_maps[[1]])

## rescale values and sum all together
corr_sum <- map(corr_maps, habicon::rescale_map) %>%
  # reduce to single spatraster
  do.call(c, .) %>% 
  sum(na.rm = TRUE)


# save
writeRaster(patch_sum, "shiny/app_data/output_habicon/patch_priority_all.tif", overwrite = TRUE)

writeRaster(corr_sum, "shiny/app_data/output_habicon/corridor_priority_all.tif", overwrite = TRUE)
```

## Census Data

Define variables to pull

```{r}
# pull the datasets 
  acs <- tidycensus::get_acs(
    geography = "block group",
    state = "CO",
    county = "Larimer",
    geometry = TRUE,
    variables = c(
      # under 5
      "B01001_003",
      "B01001_027",
      # over 64
      paste0("B01001_0", 20:25),
      paste0("B01001_0", 44:49),
      #percent people of color
      "B03002_001",
      "B03002_003",
      #Percent low income
      "C17002_001",
      "C17002_008",
      # Median household income
      "B19013_001",
      #Percent linguistic isolation
      "C16002_001",
      "C16002_004",
      "C16002_007",
      "C16002_010",
      "C16002_013",
      #Percent less than high school education
      "B15002_001",
      paste0("B15002_00", 2:9),
      "B15002_010",
      paste0("B15002_0", 20:27),
      #Percent disability
      paste0("B18101_", c("001","004","007","010","013","016","019","023",
                          "026","029","032","035","038")),
      #total Population
      "B01003_001",
      # lead housing 
      "B25034_001", # total housing units 
      "B25034_009", # 1950-1959
      "B25034_010", # 1940-1949
      "B25034_011", # pre 1939
      # housing burden
      "B25070_001", # Total Renters
      "B25070_007", # 30 to 34.9%
      "B25070_008", # 35 to 39.9%
      "B25070_009", # 40 to 49.9%
      "B25070_010", # 50% or more
      "B25091_001", # total owner-occupied,
      # "B25003_002", # confirmation of previous var - total owner occupied,
      "B25091_008", # 30 to 34.9% - mortgaged
      "B25091_009", # 35 to 39.9% - mortgaged
      "B25091_010", # 40 to 49.9% - mortgaged
      "B25091_011", # 50% or more - mortgaged
      "B25091_019", # 30 to 34.9% - not mortgaged
      "B25091_020", # 35 to 39.9% - not mortgaged
      "B25091_021", # 40 to 49.9% - not mortgaged
      "B25091_022" # 50% or more - not mortgaged
    )
  ) 
```

### Calculate, clean and save final ACS data

```{r}
cleaned_acs <- acs %>% 
  select(GEOID, NAME, variable, estimate) %>%
  pivot_wider(names_from = variable, values_from = estimate) %>% 
  # calculate variables
  group_by(GEOID) %>% 
  mutate(
    # HOUSING BURDEN
    HHUnits = B25070_001+B25091_001, # renter total + owner total
      housing_burden = B25070_007+B25070_008+B25070_009+B25070_010+
        B25091_008+B25091_009+B25091_010+B25091_011+
        B25091_019+B25091_020+B25091_021+B25091_022, # >30% renters, mortgaged, nonmortgaged
      percent_housing_burden = housing_burden/HHUnits * 100,
    # PERCENT DISABILITY
    disability = sum(B18101_004, B18101_007,
                                 B18101_010, B18101_013,
                                 B18101_016, B18101_019,
                                 B18101_023, B18101_026,
                                 B18101_029, B18101_032,
                                 B18101_035, B18101_038 ),
    percent_disability = sum(B18101_004, B18101_007,
                                 B18101_010, B18101_013,
                                 B18101_016, B18101_019,
                                 B18101_023, B18101_026,
                                 B18101_029, B18101_032,
                                 B18101_035, B18101_038 ) / B18101_001,
    # PEOPLE OF COLOR
    racial_minority = ifelse(B03002_001 == 0,
                                NA,
                                B03002_001 - B03002_003),
    percent_racial_minority = ifelse(B03002_001 == 0,
                                NA,
                                (B03002_001 - B03002_003) /
                                  B03002_001 * 100),
    # LOW INCOME
    low_income = ifelse(C17002_001 == 0, NA, C17002_001 - C17002_008),
    percent_low_income = ifelse(C17002_001 == 0, NA, (C17002_001 - C17002_008) / C17002_001 * 100),
    # population density
    area_sq_km = as.numeric(st_area(geometry)) / 1e6, # convert to sq km
    population_density = B01003_001 / area_sq_km
    ) %>% 
  dplyr::select(GEOID, NAME, total_population = B01003_001, median_income = B19013_001, housing_burden:population_density) 


#reproject for leaflet
cleaned_acs <- st_transform(cleaned_acs, 4326)

st_write(cleaned_acs, "shiny/data/acs_Larimer_2022.shp", append = FALSE)
# also save as .RDS to preserve column names for shiny app
save(cleaned_acs, file = "shiny/data/acs_Larimer_2022.RData") 
```

*No disability data for Larimer County*

## Supplemental Datasets

```{r}
# Natural Areas
nat_areas <- st_read("data/supplemental_data/Natural_Areas.shp") %>% 
  # transform
  st_transform(4326)

# Save
st_write(nat_areas, "shiny/app_data/Natural_Areas.shp")

# Parcel Owners
parcel <- st_read("data/supplemental_data/ParcelOwner.shp")

## transform and simplify
parcel_clean <- parcel %>% 
  ms_simplify(keep = 0.05)

## save as geojson
parcel_clean %>% st_transform(4326) %>% geojson_write(file = "shiny/app_data/parcel.geojson")
```
