---
title: "Indicator Metatdata"
output: github_document
---

|                                                     |                                           |                                   |                                                                                                                             |                           |                                |
|--------------|------------|------------|-----------------------|------------------------|-------------------------|
| Indicator                                           | Dataset used                              | Processing script (if applicable) | Indicator Description                                                                                                       | Time frame / last updated | Spatial resolution (if raster) |
| Impervious surface within x distance                | impervious_surfaces_fort_collins_2015.shp | src/process_preds.R               | <https://fcgov.hub.arcgis.com/datasets/hydrology-polygon>                                                                   |                           |                                |
| Land use type                                       | ?                                         | src/process_preds.R               |                                                                                                                             |                           |                                |
| Natural habitat cover within x distance             |                                           | src/process_preds.R               | <https://fcgov.hub.arcgis.com/datasets/976ba1a7e06a4f368ddda69dd736a0d9_0/explore?location=40.570454%2C-105.088218%2C13.67> |                           |                                |
| Distance to river                                   |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Vegetative cover within x distance                  |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Distance to nearest residential structure           |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Residential structure density within                |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Distance to nearest structure                       |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Green space cover within x distance                 |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Structure density within x distance                 |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Distance to nearest commercial structure            |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Green space median patch size within x distance     |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Distance to GMA boundary                            |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
| Natural habitat median patch size within x distance |                                           | src/process_preds.R               |                                                                                                                             |                           |                                |
