---
title: "Variable Metatdata"
output: github_document
---

+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| **Indicator**            | **Metric used**                   | **File/Variable Name**   | **Indicator Description or Citation (access link if available)**                                                                                                                                               | **Time frame / last updated** | **Spatial resolution (if raster)** |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Informal Greenspace      | Percent cover (3x3 moving window) | lc_inf_greenspace.tif    | Greenspace that is not formally owned or managed. Data produced by Co-PI [Sara Bombaci's](https://sites.warnercnr.colostate.edu/sbombaci/) lab group.                                                          | 2024                          | Shapefile                          |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Natural Areas            | Distance to (m)                   | Natural_Areas.shp        | City and County owned and/or managed Natural Areas for the area around Fort Collins (<https://fcgov.hub.arcgis.com/datasets/natural-areas/explore>)                                                            | 2025                          | Shapefile                          |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Wetlands                 | Distance to (m)                   | cnhp_foco_wetlands.shp   | Colorado Wetlands Inventory Mapping Tool. Includes wetland, riparian, fen and playa mapping.                                                                                                                   | 2009                          | Shapefile                          |
|                          |                                   |                          |                                                                                                                                                                                                                |                               |                                    |
|                          |                                   |                          | [Colorado Wetland Inventory](https://csurams.maps.arcgis.com/apps/webappviewer/index.html?id=a8e43760cb934a5084e89e46922580cc)                                                                                 |                               |                                    |
|                          |                                   |                          |                                                                                                                                                                                                                |                               |                                    |
|                          |                                   |                          | [Dataset](https://cnhp.colostate.edu/arcgis/rest/services/Wetland_Inv/Wetlands/MapServer)                                                                                                                      |                               |                                    |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Building Cover           | Distance to (m)                   | Buildings.shp            | Building footprints for the City of Fort Collins (<https://fcgov.hub.arcgis.com/datasets/fcgov>::buildings/about)                                                                                              | 2025                          | Shapefile                          |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Canopy Cover             | Percent cover (3x3 moving window) | lc_TreeCanopy.tif        | [Rasmussen S, Tinkam W, and McHale MR. 2022. What can a medium sized semi-arid city teach us about human-made forests? Urban Ecosystems (2022).](https://link.springer.com/article/10.1007/s11252-022-01203-0) | 2016                          | 1m                                 |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Grass/Shrub Cover        | Percent cover (3x3 moving window) | lc_Grass_Shrubs.tif      | [Rasmussen S, Tinkam W, and McHale MR. 2022. What can a medium sized semi-arid city teach us about human-made forests? Urban Ecosystems (2022)](https://link.springer.com/article/10.1007/s11252-022-01203-0). | 2016                          | 1m                                 |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Impervious Surface Cover | Percent cover (3x3 moving window) | lc_OtherPaved.tif        | Data produced by Co-PI [Sara Bombaci's](https://sites.warnercnr.colostate.edu/sbombaci/) lab group.                                                                                                            | 2024                          | 1m                                 |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Roads                    | Distance to (m)                   | lc_Roads_Railroads.tif   | Data produced by Co-PI [Sara Bombaci's](https://sites.warnercnr.colostate.edu/sbombaci/) lab group.                                                                                                            | 2024                          | 1m                                 |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
| Green Space Cover        | Percent cover (3x3 moving window) | nic_green_space_2015.shp | Formal greenspace, inclusive of natural areas and natural habitat provided by the City of Fort Collins Nature in the City Program                                                                              | 2015                          | Shapefile                          |
+--------------------------+-----------------------------------+--------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+------------------------------------+
